### ISSUE TITLE
Apply license statement

### ISSUE THREAD

**Issue by jmcgeheeiv** [KyleJamesWalker/yamlsettings#10]
We are very interested in using yamlsettings in our product.  However, without a license statement, we cannot.

I recommend the Apache license, but that is of course up to you.  If you choose Apache please [add LICENSE and NOTICE files](http://www.apache.org/dev/apply-license.html#new) and [add headers to the files](http://www.apache.org/licenses/LICENSE-2.0.html#apply).

If you find the Apache license acceptable, tell me so and I will make the updates for you via a pull request.

**Comment by gullpong** [comment]
https://github.com/KyleJamesWalker/yamlsettings/blob/master/setup.py#L34

Since It's mentioned in the setup.py, we think it should be good enough.
But if needed we'll put the license and the notice file in the repo.

**Comment by KyleJamesWalker** [comment]
@jmcgeheeiv Is the attached PR good enough for your use case, not sure how I missed adding the `LICENSE` file into the repo, I normally try and make all my projects `MIT`.

If this works I'll merge the changes into master.

**Comment by jmcgeheeiv** [comment]
Thank you for your attention.

The MIT license would be just fine.  I found some [instructions on how to properly apply the MIT license](https://code.google.com/p/icrl/wiki/ApplyingMITlicense).

**Comment by KyleJamesWalker** [comment]
Thanks I'll make the needed updates so it complies with those pesky lawyers. :P

**Comment by KyleJamesWalker** [comment]
Updated PR, and based the text on: https://opensource.org/licenses/MIT

If that looks good to you, let me know and I'll merge and push a new version.

Thanks

**Comment by jmcgeheeiv** [comment]
That looks just fine.

**Comment by KyleJamesWalker** [comment]
Updated, Merged and Uploaded to [Pypi](https://pypi.python.org/pypi/yamlsettings/0.2.4), thanks.

**Comment by jmcgeheeiv** [comment]
Thank you.
